version: '3.7'

volumes:
    storage:
        external: false
        name: omdico-storage
    database:
        external: false
        name: omdico-database
    redis_cache:
        external: false
        name: omdico-redis-cache

services:
    app:
        image: omdico-backend:latest
        dns:
            - 8.8.8.8
        extra_hosts:
        - "host.docker.internal:host-gateway"
        build:
            context: .
            dockerfile: ./dockerfile
        container_name: omdico-backend
        env_file: .env
        restart: unless-stopped
        user: "www-data"
        depends_on:
            - db 
            - redis 
        volumes:
            - storage:/app/storage
    
    default-queue:
        image: omdico-backend:latest
        build:
            context: .
            dockerfile: ./dockerfile
        container_name: "omdico-default-queue"
        env_file: .env
        restart: unless-stopped
        entrypoint: php artisan queue:work --daemon
        depends_on:
            - app

    nginx:
        image: nginx
        container_name: omdico-rproxy
        ports:
            - 9241:80
        restart: unless-stopped
        volumes:
            - ./docker_nginx.conf:/etc/nginx/nginx.conf:ro

    db:
        image: mysql:8.0
        container_name: omdico-db
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=omdico
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - 0.0.0.0:6852:3306
        restart: unless-stopped
    
    redis:
        image: redis:alpine
        container_name: omdico-redis
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        volumes:
        - redis_cache:/data