name: CI Deployment

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - name: SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.TEST_SERVER_HOST }}
        username: ${{ secrets.TEST_SERVER_USERNAME }}
        key: ${{ secrets.TEST_SERVER_KEY }}
        port: ${{ secrets.TEST_SERVER_PORT }}
        script: sudo bash -c "cd /home/projects/omdico/omdico-backend && git pull origin main && bash .github/workflows/main-deploy.sh"
