name: CI Deployment

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TEST_SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.TEST_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Start SSH Agent
        run: eval $(ssh-agent -s)

      - name: Add SSH key to agent
        run: ssh-add ~/.ssh/id_rsa

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          key: ${{ secrets.TEST_SERVER_KEY }}
          port: ${{ secrets.TEST_SERVER_PORT }}
          script: |
            cd /home/projects/omdico/omdico-backend
            git pull origin main
            bash .github/workflows/main-deploy.sh
